"""Tests for marketplace/api/v2_events.py -- event stream bootstrap endpoints.

All endpoints hit the real FastAPI app via the ``client`` fixture.
Stream tokens are generated by the real auth module. No external services
to mock.
"""

from __future__ import annotations

from marketplace.config import settings
from marketplace.core.auth import decode_stream_token


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _auth(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


# ===========================================================================
# GET /api/v2/events/stream-token
# ===========================================================================


async def test_stream_token_happy_path(client, make_agent):
    """GET /stream-token returns a valid stream token for the agent."""
    agent, token = await make_agent()

    resp = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token),
    )
    assert resp.status_code == 200
    body = resp.json()
    assert body["agent_id"] == agent.id
    assert "stream_token" in body
    assert "expires_in_seconds" in body
    assert "expires_at" in body
    assert body["ws_url"] == "/ws/v2/events"
    assert body["allowed_topics"] == ["public.market", "private.agent"]


async def test_stream_token_is_valid_jwt(client, make_agent):
    """The returned stream_token should be decodable."""
    agent, token = await make_agent()

    resp = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token),
    )
    assert resp.status_code == 200
    stream_token = resp.json()["stream_token"]

    payload = decode_stream_token(stream_token)
    assert payload["sub"] == agent.id
    assert payload["type"] == "stream_agent"
    assert "public.market" in payload["allowed_topics"]
    assert "private.agent" in payload["allowed_topics"]


async def test_stream_token_expires_in_matches_settings(client, make_agent):
    """The expires_in_seconds should match the configured setting."""
    _, token = await make_agent()

    resp = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token),
    )
    assert resp.status_code == 200
    body = resp.json()
    expected_seconds = int(settings.stream_token_expire_minutes * 60)
    assert body["expires_in_seconds"] == expected_seconds


async def test_stream_token_rejects_missing_auth(client):
    """GET /stream-token without auth returns 401."""
    resp = await client.get("/api/v2/events/stream-token")
    assert resp.status_code == 401


async def test_stream_token_rejects_invalid_token(client):
    """GET /stream-token with invalid token returns 401."""
    resp = await client.get(
        "/api/v2/events/stream-token",
        headers={"Authorization": "Bearer garbage-token"},
    )
    assert resp.status_code == 401


async def test_stream_token_rejects_creator_token(client, make_creator):
    """Creator tokens must not authenticate on agent-only endpoints."""
    _, creator_token = await make_creator()
    resp = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(creator_token),
    )
    assert resp.status_code == 401


async def test_stream_token_rejects_malformed_header(client):
    """GET /stream-token with malformed auth header returns 401."""
    resp = await client.get(
        "/api/v2/events/stream-token",
        headers={"Authorization": "Basic dXNlcjpwYXNz"},
    )
    assert resp.status_code == 401


async def test_stream_token_different_agents_get_different_tokens(client, make_agent):
    """Different agents should receive different stream tokens."""
    agent_a, token_a = await make_agent(name="agent-a")
    agent_b, token_b = await make_agent(name="agent-b")

    resp_a = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token_a),
    )
    resp_b = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token_b),
    )
    assert resp_a.status_code == 200
    assert resp_b.status_code == 200
    assert resp_a.json()["agent_id"] == agent_a.id
    assert resp_b.json()["agent_id"] == agent_b.id
    assert resp_a.json()["stream_token"] != resp_b.json()["stream_token"]


async def test_stream_token_expires_at_is_iso_format(client, make_agent):
    """The expires_at field should be a parseable ISO datetime string."""
    _, token = await make_agent()

    resp = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token),
    )
    assert resp.status_code == 200
    expires_at = resp.json()["expires_at"]
    assert "T" in expires_at


async def test_stream_token_cannot_be_used_for_api_auth(client, make_agent):
    """A stream token must not work for regular API endpoints."""
    _, token = await make_agent()

    resp = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(token),
    )
    stream_token = resp.json()["stream_token"]

    resp2 = await client.get(
        "/api/v2/events/stream-token",
        headers=_auth(stream_token),
    )
    assert resp2.status_code == 401
